# Creates a new image version when a new version of the devvm.json file is created.
name: Test

# Run the workflow only when the devvm.json file has been updated in the master branch.
on:
  push:
    branches: [ master ]
    paths: .test/test.json

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Dump-Contexts:
    runs-on: ubuntu-latest
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2

    - name: Get TestJson
      run: echo fromJson(`cat ./.test/test.json`).version