# Creates a new image version when a new version of the devvm.json file is created.
name: Create Image Version

# Run the workflow only when the devvm.json file has been updated in the master branch.
on:
  push:
    branches: [ master ]
    paths: .test/test.json

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    name: Initialize
    runs-on: ubuntu-latest
    outputs:
      devvm: ${{ fromJson(steps.set-config.outputs.config) }

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      id: set-config
      run: |
        content=`cat ./.test/test.json`
        # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        # end of optional handling for multi line json
        echo "::set-output name=devvm::$content"

  create:
    name: Create Image Version
    needs: init
    runs-on: ubuntu-latest

    steps:
    - name: Validate
      run: echo "Version '${{ needs.init.outputs.devvm.version }}'"
