# Creates a new image version when a new version of the devvm.json file is created.
name: Create Image Version

# Run the workflow only when the devvm.json file has been updated in the master branch.
on:
  push:
    branches: [ master ]
#    paths: .test/test.json

env:
  # Put here for testing only. It is not meant to stay here, but instead randomly selected from pool.
  SUB_ID: e605a3bc-ee4e-4c7a-9709-1868a28b1d4d

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  init:
    name: Initialize
    runs-on: ubuntu-latest
    outputs:
      devvm: ${{ steps.set-config.outputs.config }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      id: set-config
      run: |
        content=`cat ./.test/test.json`
        # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        # end of optional handling for multi line json
        echo "::set-output name=config::$content"

  setup:
    name: Configure Environment
    needs: init
    runs-on: ubuntu-latest
    env:
      RG_NAME: lv-rg-${{ github.event.repository.id }}
      ID_NAME: lv-uami-${{ github.event.repository.id }}
      GAL_NAME: lv_sig_${{ github.event.repository.id }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

#    - name: Azure Login
#      uses: azure/login@v1
#      with:
#        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
#    - name: Azure CLI script
#      uses: azure/CLI@v1
#      with:
#        azcliversion: 2.0.72
#        inlineScript: |
    - name: Dump Variables
      run: |
        echo $SUB_ID
        echo $RG_NAME
        echo $ID_NAME
        echo $GAL_NAME
        echo $IMG_NAME
        git ls-files ./.test/test.json

  create:
    name: Create Image Version
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Validate
      run: "echo Version: ${{ fromJson(needs.init.outputs.devvm).version }}"
